---
apt_upgrade: "no"
apt_autoremove: true
copy_keys_to_hosts: true

apt_install_common: false

pip_install: false

apt_common:
    - htop
    - iotop
    - gcc 
    - make 
    - wget
    - curl 
    - g++
    - git
    - gzip
    - unzip
    - rsync
apt_additional: []
apt_remove: []

pip_for_users:
    - matplotlib
    - numpy
    - imutils
    - requests
    - progressbar2
pip_for_user_additional: []
pip_for_root: []
pip_for_root_additional: []
