---
- hosts: mail
  become: yes
  vars_files:
    - ../vars/secrets.yml

  roles:
    - role: roles/basic/users
    - role: roles/basic/packages
      vars:
        - apt_install_common: true
    - role: roles/backup/rsync